disabled_rules:
  - line_length

opt_in_rules:
  - array_init
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - fatal_error_message
  - first_where
  - operator_usage_whitespace
  - sorted_first_last
  - sorted_imports

excluded:
  - Pods
